### ISSUE TITLE
Resonsive rendering of question limited

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#81] opened 2017-01-30 07:55 UTC
The questions are not responsive enough to deal with common mobile screens. See this screenshot from a Fairphone 2:
![screenshot_2017-01-30-01-30-39](https://cloud.githubusercontent.com/assets/7458098/22415723/deeb4b24-e6c9-11e6-9e9d-9b0e050a69a8.png)

**Comment by andreabettich** [comment] 2017-01-30 18:42
Can't reproduce on chrome dev tools

**Comment by nicorikken** [comment] 2017-01-30 18:59
Neither can I with the Firefox tools. Let's leave it at that then.

**Comment by andreabettich** [comment] 2017-02-10 21:04
I'll close this issue.

**Closed by andreabettich** 2017-02-10 21:04 UTC
Labels: bug
